Repository TeamSodam/sodam-client, pull requests merged in 2022-03, with the labels that each got.

#116 [#115] E#X-S#1 CSR로 변경한 코드 구조 다듬기 및 수정
  src/components/MapSidebar/ShopElement.tsx
  src/components/review/OtherReview/Container/index.tsx
  src/components/review/OtherReview/Presentation/OtherMyScrapReview.tsx
  src/components/review/OtherReview/Presentation/OtherMyWriteReview.tsx
  src/components/review/OtherReview/Presentation/OtherShopReview.tsx
  src/components/review/OtherReview/Presentation/index.tsx
  src/components/review/OtherReviewCard.tsx
  src/components/review/ReviewDetailCard.tsx
  src/pages/index.tsx
  src/pages/map/[areaId].tsx
  src/pages/review/detail/[reviewId].tsx
  src/pages/review/my/scrap.tsx
Labels: :construction: refactor, :3rd_place_medal:, 혁진, 🔫 리뷰중

#118 [#117] E#X-S#4 소품샵검색API 디바운스
  package.json
  src/components/review/ShopSearch.tsx
  yarn.lock
Labels: :sparkles: feature, :3rd_place_medal:, 혁진, 🔫 리뷰중

#120 [#115] E#11-S#5 회원가입 뷰 구현 (확정 전)
  src/components/Auth/SignupForm.tsx
  src/components/Auth/SignupOption.tsx
  src/components/Auth/ThemeSelector.tsx
  src/components/common/PersonalInfoInput.tsx
  src/hooks/useInfoType.ts
  src/hooks/useInput.ts
  src/pages/auth/join.tsx
  src/types/user.ts
Labels: :sparkles: feature, :3rd_place_medal:, 희선, 🔫 리뷰중

#122 [#119] [FEATURE] E#12-S#1 데스크탑 그리드 세팅
  public/assets/ic_search_desktop.svg
  public/assets/mainLogoDesktop.svg
  src/components/common/Navbar/GlobalNav.tsx
  src/hooks/useMedia.tsx
  src/styles/Screen.tsx
  src/styles/mediaQuery.ts
Labels: :sparkles: feature, :2nd_place_medal:, 혁진, 🔫 리뷰중
