Repository TeamSodam/sodam-client, pull requests merged in 2022-05, with the labels that each got.

#139 [#138] [BUG] E#X-S#X image 예외 처리
  src/components/MapSidebar/ShopElement.tsx
  src/components/common/ReviewCard.tsx
  src/components/common/ShopCard.tsx
  src/map/overlays/tooltip.tsx
  src/pages/shop/detail/[id].tsx
  src/types/review.ts
  src/types/shop.ts
  src/utils/loadImageSafely.ts
  src/utils/parseCategorySafely.ts
Labels: :bug: bug, :1st_place_medal:, 혁진, 🔫 리뷰중

#140 [#131] E#11-S#5 로그인 뷰 구현
  public/assets/ic_check.svg
  public/assets/ic_minus.svg
  public/assets/ic_plus.svg
  public/assets/ic_themeCuteJoin.png
  public/assets/ic_themeCuteJoinOff.png
  public/assets/ic_themeHipJoin.png
  public/assets/ic_themeHipJoinOff.png
  public/assets/ic_themeModernJoin.png
  public/assets/ic_themeModernJoinOff.png
  public/assets/ic_themeVintageJoin.png
  public/assets/ic_themeVintageJoinOff.png
  src/components/Auth/AcceptTerms.tsx
  src/components/Auth/SignupForm.tsx
  src/components/Auth/SignupOption.tsx
  src/components/Auth/TermsContents.ts
  src/components/Auth/ThemeItem.tsx
  src/components/Auth/ThemeSelector.tsx
  src/components/common/PersonalInfoInput.tsx
  src/constants/joinInfoList.ts
  src/hooks/useInfoType.ts
  src/hooks/useInput.ts
  src/pages/auth/join.tsx
  src/pages/auth/login.tsx
  src/styles/theme.ts
  src/types/user.ts
Labels: :sparkles: feature, :2nd_place_medal:, 희선, 🔫 리뷰중

#152 [#124][FEATURE] E#12-S#3 데스크탑 카드 반응형
  src/components/common/MainSlider.tsx
  src/components/common/ReviewCard.tsx
  src/components/common/ShopCard.tsx
  src/components/common/ShopCardRank.tsx
  src/pages/index.tsx
Labels: :sparkles: feature, :3rd_place_medal:, 소희, 🔫 리뷰중

#141 [#137] [FEATURE] E#13-S#3 지도 페이지 반응형
  src/components/ImageMap/index.tsx
  src/components/LocalShopInfo/OptionList.tsx
  src/components/LocalShopInfo/ShopElement.tsx
  src/components/LocalShopInfo/ShopList.tsx
  src/components/LocalShopInfo/index.tsx
  src/components/MapSidebar/index.tsx
  src/features/map/mapSlice.ts
  src/hooks/useMap.tsx
  src/map/data/latlng.ts
  src/map/overlays/tooltip.tsx
  src/map/utils/display.ts
  src/map/utils/search.ts
  src/pages/map/[areaId].tsx
  src/styles/mediaQuery.ts
Labels: :1st_place_medal:, 혁진, 🔫 리뷰중

#147 [FEATURE] E#14-S#1~6 마이페이지 기능 완성 + 반응형 구현
  public/assets/ic_minus.png
  public/assets/ic_plus.png
  public/assets/ic_theme_cute_off.png
  public/assets/ic_theme_cute_on.png
  public/assets/ic_theme_hip_off.png
  public/assets/ic_theme_hip_on.png
  public/assets/ic_theme_modern_off.png
  public/assets/ic_theme_modern_on.png
  public/assets/ic_theme_vintage_off.png
  public/assets/ic_theme_vintage_on.png
  public/assets/profile_default.svg
  src/app/store.ts
  src/components/Mypage/UserInfoInput.tsx
  src/components/Mypage/UserInfoWrap.tsx
  src/components/Mypage/UserTheme.tsx
  src/components/Mypage/UserThemeItem.tsx
  src/components/common/Layout.tsx
  src/components/common/Navbar/GlobalNav/Desktop.tsx
  src/components/common/Navbar/GlobalNav/Mobile.tsx
  src/components/common/Navbar/GlobalNav/index.tsx
  src/features/users/userApi.ts
  src/pages/mypage.tsx
  src/styles/globalStyle.ts
  src/styles/theme.ts
  src/types/user.ts
  src/utils/cropImage.tsx
  src/utils/dataURItoBlob.tsx
Labels: :sparkles: feature, :2nd_place_medal:, 소희, 🔫 리뷰중
