Repository TeamSodam/sodam-client, pull requests merged in 2022-01, with the labels that each got.

#4 [#3] E#0 S#4 카카오맵 API 관련 사전세팅
  .babelrc
  .env
  next.config.js
  public/assets/activeMarker.svg
  public/assets/marker.svg
  src/hooks/.keep
  src/hooks/useMap.tsx
  src/map/.keep
  src/map/overlays/tooltip.tsx
  src/map/utils/display.ts
  src/map/utils/search.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/mapTesting.tsx
  src/pages/my.tsx
  src/styles/globalStyle.ts
  src/styles/theme.ts
  src/types/.keep
  src/types/map.ts
  src/types/styled.d.ts
  tsconfig.json
Labels: :sparkles: feature, :1st_place_medal:, 혁진

#10 [#5] E#1 S#4 카드 구현
  public/assets/ex_profile.jpg
  public/assets/ic_heart.svg
  public/assets/ic_rank_1.svg
  public/assets/ic_rank_2.svg
  public/assets/ic_rank_3.svg
  public/assets/ic_save.svg
  src/components/common/.keep
  src/components/common/ImageDiv.tsx
  src/components/common/ReviewCard.tsx
  src/components/common/ShopCard.tsx
  src/components/common/ShopCardRank.tsx
  src/styles/globalStyle.ts
  src/styles/mediaQuery.ts
  src/styles/theme.ts
  src/types/review.ts
  src/types/shop.ts
Labels: :sparkles: feature, :1st_place_medal:, 소희

#14 [#7] [FEATURE] E#1-S#5 페이지 flow 생성
  src/pages/auth/join.tsx
  src/pages/auth/login.tsx
  src/pages/map/[areaId].tsx
  src/pages/map/index.tsx
  src/pages/mypage.tsx
  src/pages/review/detail/[id].tsx
  src/pages/review/my/scrap.tsx
  src/pages/review/my/write.tsx
  src/pages/review/write.tsx
  src/pages/shop/collect.tsx
  src/pages/shop/detail/[id].tsx
  src/pages/shop/theme/[type].tsx
  tsconfig.json
Labels: :sparkles: feature, :1st_place_medal:, 희선

#16 [#13] [FEATURE] E#2-S#1 이미지 지도 구현
  src/components/ImageMap/index.tsx
  src/constants/.keep
  src/constants/SeoulAreaEnum.ts
  src/pages/map/[areaId].tsx
  src/pages/map/index.tsx
  src/styles/globalStyle.ts
Labels: :sparkles: feature, :1st_place_medal:, 혁진

#11 [#6] [FEATURE] E#1-S#3 Redux 구조 세팅
  mock-api.json
  public/assets/dummy/dummy-image.jpg
  public/assets/dummy/dummy-shop.png
  routes.json
  src/app/store.ts
  src/constants/SeoulAreaEnum.ts
  src/features/reviews/reviewApi.ts
  src/features/shops/shopApi.ts
  src/features/users/userSlice.ts
  src/libs/api.ts
  src/types/review.ts
  src/types/shop.ts
  src/types/user.ts
Labels: :sparkles: feature, :1st_place_medal:, 혁진

#25 [#9] [FEATURE] E#1-S#2 Footer 구현
  public/assets/footerLogo.svg
  src/components/common/Footer.tsx
  src/constants/sodamContactList.ts
  src/constants/sodamDocList.ts
  src/pages/_app.tsx
Labels: :sparkles: feature, :1st_place_medal:, 주희

#19 [#12] [FEATURE] E#5-S#1 슬라이더 구현
  .vscode/settings.json
  package.json
  public/assets/ex_thumbnail.png
  public/assets/ic_next.svg
  public/assets/ic_next_round.svg
  public/assets/ic_prev.svg
  public/assets/ic_prev_round.svg
  src/components/common/MainSlider.tsx
  src/components/review/ImageCard.tsx
  src/components/review/ImageSlider.tsx
  src/pages/sliderTesting.tsx
  yarn.lock
Labels: :sparkles: feature, :1st_place_medal:, 소희

#20 [#17] [FEATURE] E#2-S#2,3 커스텀마커 & 사이드바
  .babelrc
  package.json
  public/assets/activeMarker.svg
  public/assets/ic_active_marker.svg
  public/assets/ic_basic_marker.svg
  public/assets/ic_delimiter.svg
  public/assets/ic_empty_star.svg
  public/assets/ic_leftArr.svg
  public/assets/ic_star.svg
  public/assets/marker.svg
  src/components/ImageMap/index.tsx
  src/components/MapSidebar/ShopElement.tsx
  src/components/MapSidebar/index.tsx
  src/constants/dummy.ts
  src/features/map/mapSlice.ts
  src/hooks/useMap.tsx
  src/map/overlays/tooltip.tsx
  src/map/utils/display.ts
  src/map/utils/search.ts
  src/pages/map/[areaId].tsx
  src/reducers/index.ts
  src/types/image.d.ts
  src/types/map.ts
  tsconfig.json
  yarn.lock
Labels: :sparkles: feature, :1st_place_medal:, 혁진

#22 [#15] [FEATURE] E#5-S#2 테마 카테고리 컴포넌트 구현
  public/assets/ic_themeCute.png
  public/assets/ic_themeCuteOn.png
  public/assets/ic_themeHip.png
  public/assets/ic_themeHipOn.png
  public/assets/ic_themeModern.png
  public/assets/ic_themeModernOn.png
  public/assets/ic_themeVintage.png
  public/assets/ic_themeVintageOn.png
  src/components/ThemeSelector/ThemeElement.tsx
  src/components/ThemeSelector/index.tsx
Labels: :sparkles: feature, :1st_place_medal:, 희선

#27 [#23] [FEATURE] E#5-S#3 드롭다운 필터 뷰 구현
  public/assets/ic_dropdown.svg
  src/components/common/DropDownFilter.tsx
  src/components/common/FilterDiv.tsx
  src/components/common/MoreFilter.tsx
  src/constants/dropdownOptionList.ts
  src/types/shop.ts
Labels: :sparkles: feature, :1st_place_medal:, 희선

#28 [#21] [FEATURE] E#2-S#2,3 지도 UI 개선 & 데이터 API 설계
  mock-api.json
  public/assets/ic_delimiter.svg
  src/components/MapSidebar/ShopElement.tsx
  src/components/MapSidebar/index.tsx
  src/features/shops/shopApi.ts
  src/hooks/useMap.tsx
  src/map/overlays/tooltip.tsx
  src/map/utils/display.ts
  src/pages/map/[areaId].tsx
  src/pages/shop/detail/[id].tsx
  src/types/map.ts
  src/types/shop.ts
Labels: :sparkles: feature, :2nd_place_medal:, 혁진

#32 [#29] [FEATURE] E#6-S#1 소품샵 상세지도
  public/assets/ic_address_land.svg
  public/assets/ic_address_road.svg
  public/assets/ic_copy.svg
  public/assets/ic_land_address.svg
  public/assets/ic_road_address.svg
  routes.json
  src/components/DetailShopAddress/index.tsx
  src/components/MapSidebar/ShopElement.tsx
  src/features/map/mapSlice.ts
  src/features/shops/shopApi.ts
  src/hooks/useMap.tsx
  src/map/overlays/miniTooltip.tsx
  src/map/overlays/tooltip.tsx
  src/map/utils/display.ts
  src/map/utils/search.ts
  src/pages/map/[areaId].tsx
  src/pages/shop/detail/[id].tsx
  src/styles/globalStyle.ts
Labels: :sparkles: feature, :2nd_place_medal:, 혁진

#38 [#30] [FEATURE] E#3-S#3 리뷰작성 구매한 소품 입력 뷰 구현
  public/assets/ic_search.svg
  src/components/WriteItems/BuyList.tsx
  src/components/WriteItems/DropdownItem.tsx
  src/components/WriteItems/DropdownPrice.tsx
  src/components/WriteItems/ItemsListDiv.tsx
  src/components/WriteItems/PriceList.tsx
  src/components/WriteItems/index.tsx
  src/constants/dropdownOptionList.ts
Labels: :sparkles: feature, :2nd_place_medal:, 희선, 🔫 리뷰중

#35 [#34] [FEATURE] E#7-S#1 메인페이지 컴포넌트 배치
  mock-api.json
  public/assets/main_banner.svg
  public/assets/main_banner_btn.svg
  src/components/DetailShopAddress/index.tsx
  src/components/MapSidebar/ShopElement.tsx
  src/components/MapSidebar/index.tsx
  src/components/ThemeSelector/index.tsx
  src/components/common/Banner.tsx
  src/components/common/MainSlider.tsx
  src/components/common/ReviewCard.tsx
  src/components/common/ShopCard.tsx
  src/constants/dropdownOptionList.ts
  src/features/reviews/reviewApi.ts
  src/features/shops/shopApi.ts
  src/features/users/userSlice.ts
  src/hooks/useMap.tsx
  src/map/overlays/miniTooltip.tsx
  src/map/overlays/tooltip.tsx
  src/map/utils/display.ts
  src/pages/index.tsx
  src/pages/mapTesting.tsx
  src/pages/shop/theme/[type].tsx
  src/pages/sliderTesting.tsx
  src/types/review.ts
  src/types/shop.ts
Labels: :sparkles: feature, :1st_place_medal:, 혁진, 🔫 리뷰중

#43 [#40] [BUG] E#6-S#1 소품샵 상세 지도 렌더링 이슈
  src/hooks/useMap.tsx
Labels: :bug: bug, :1st_place_medal:, 혁진, 🔫 리뷰중

#36 [#18] [FEATURE] E#3-S#2 리뷰 사진 등록
  .eslintrc.json
  public/assets/ic_camera.svg
  public/assets/ic_delete_round.svg
  public/assets/ic_img_delete.svg
  public/assets/ic_img_main.svg
  public/assets/ic_img_plus.svg
  public/assets/ic_img_replace.svg
  src/components/review/write/PreviewImageList.tsx
  src/components/review/write/PreviewImageMain.tsx
  src/pages/review/write.tsx
  src/types/review.ts
Labels: :sparkles: feature, :1st_place_medal:, 소희, 🔫 리뷰중

#41 [#26] [FEATURE] E#4-S#1 리뷰 상세 뷰 퍼블리싱 #26
  mock-api.json
  public/assets/ic_likeReview.svg
  public/assets/ic_likeReviewClicked.svg
  public/assets/ic_scrapReview.svg
  public/assets/ic_scrapReviewClicked.svg
  routes.json
  src/components/common/FilterDiv.tsx
  src/components/review/ImageSlider.tsx
  src/components/review/OtherReviewCard.tsx
  src/components/review/ReviewDetailCard.tsx
  src/features/reviews/reviewApi.ts
  src/pages/review/detail/[id].tsx
  src/pages/review/detail/[reviewId].tsx
  src/types/review.ts
Labels: :sparkles: feature, :1st_place_medal:, 주희, 🔫 리뷰중

#42 [#39] E#3-S#3 리뷰작성 구매한 소품 입력 기능 구현
  src/components/WriteItems/BuyList.tsx
  src/components/WriteItems/DropdownItem.tsx
  src/components/WriteItems/DropdownPrice.tsx
  src/components/WriteItems/index.tsx
  src/components/review/WriteItems/BuyList.tsx
  src/components/review/WriteItems/DropdownItem.tsx
  src/components/review/WriteItems/DropdownPrice.tsx
  src/components/review/WriteItems/ItemsListDiv.tsx
  src/components/review/WriteItems/PriceList.tsx
  src/components/review/WriteItems/index.tsx
Labels: :sparkles: feature, :2nd_place_medal:, 희선, 🔫 리뷰중

#50 [#49] [REFACTOR] E#1-S#1 NavBar, Footer padding 수정
  public/assets/footerLogo.svg
  src/components/common/Footer.tsx
  src/components/common/Navbar/GlobalNav.tsx
  src/components/common/Navbar/LocalNav.tsx
Labels: :construction: refactor, :1st_place_medal:, 주희, 🔫 리뷰중

#45 [#44] [FEATURE] E#7-S#2 테마별 소품샵 컴포넌트 배치
  mock-api.json
  routes.json
  src/components/ThemeSelector/index.tsx
  src/features/shops/shopApi.ts
  src/pages/shop/theme/[type].tsx
  src/types/shop.ts
Labels: :sparkles: feature, :1st_place_medal:, 혁진, 🔫 리뷰중

#52 [#47] [FEATURE] E#4-S#2 좋아요/스크랩 기능
  mock-api.json
  src/components/review/OtherReviewCard.tsx
  src/components/review/ReviewDetailCard.tsx
  src/pages/review/detail/[reviewId].tsx
Labels: :sparkles: feature, :1st_place_medal:, 주희, 🔫 리뷰중

#59 [#53] [FEATURE] E#7-S#6 마이리뷰 - 내가 작성한 리뷰 페이지 구현
  mock-api.json
  public/assets/ic_writeReview.svg
  src/components/common/WriteReviewBtn.tsx
  src/pages/review/my/write.tsx
Labels: :sparkles: feature, :1st_place_medal:, 희선, 🔫 리뷰중

#58 [#55] [FEATURE] E#7-S#8 컨텐츠 없음 페이지들
  public/assets/img_scrapNoContent.png
  public/assets/img_shopNoContent.png
  public/assets/img_writeNoContent.png
  src/components/common/EmptyContent.tsx
  src/components/common/Navbar/GlobalNav.tsx
  src/components/common/Navbar/LocalNav.tsx
  src/pages/review/my/emptyScrap.tsx
  src/pages/review/my/emptyWrite.tsx
  src/pages/shop/collect.tsx
  src/pages/shop/empty.tsx
Labels: :sparkles: feature, :1st_place_medal:, 주희, 🔫 리뷰중

#61 [#57] [FEATURE] E#7-S#7 소품샵상세페이지 하단 슬라이더
  mock-api.json
  public/assets/ic_leftArrow.svg
  public/assets/ic_rightArrow.svg
  routes.json
  src/components/common/DropDownFilter.tsx
  src/components/common/PageNaviagator.tsx
  src/features/reviews/reviewApi.ts
  src/features/shops/shopApi.ts
  src/pages/shop/detail/[id].tsx
  src/types/review.ts
Labels: :sparkles: feature, :1st_place_medal:, 혁진, 🔫 리뷰중

#51 [#31] [FEATURE] E#3-S#3 리뷰 작성 소품샵 이름 검색 구현
  public/assets/ic_searchDel.svg
  routes.json
  src/components/review/ShopSearch.tsx
  src/components/review/ShopSearchList.tsx
  src/features/shops/shopApi.ts
Labels: :sparkles: feature, :3rd_place_medal:, 희선, 🔫 리뷰중

#65 [#62] [FEATURE] E#7-S#3 저장한 소품샵 페이지 구현
  src/pages/shop/collect.tsx
Labels: :sparkles: feature, :1st_place_medal:, 희선, 🔫 리뷰중

#67 bug: :bug: Navbar 라우팅 수정 #64
  src/components/common/Navbar/GlobalNav.tsx
  src/pages/shop/collectEmpty.tsx
Labels: :bug: bug, :1st_place_medal:, 주희, 🔫 리뷰중

#74 [#71] [FEATURE] E#9-S#3 저장한 소품샵 API 연결
  src/components/common/ShopCard.tsx
  src/features/shops/shopApi.ts
  src/pages/shop/collect.tsx
  src/types/api.ts
  src/types/shop.ts
Labels: :sparkles: feature, :1st_place_medal:, 희선, 🔫 리뷰중

#72 [#68] [FEATURE] E#9-S#1 테마별소품샵 API 연결
  .env
  mock-api.json
  src/features/shops/shopApi.ts
  src/pages/shop/theme/[type].tsx
Labels: :sparkles: feature, :1st_place_medal:, 혁진, 🔫 리뷰중

#77 [#73] [FEATURE] E#9-S#6 소품샵 상세페이지 API 연결
  next.config.js
  src/features/shops/shopApi.ts
  src/pages/shop/detail/[id].tsx
Labels: :sparkles: feature, :1st_place_medal:, 혁진, 🔫 리뷰중

#83 [#75] [FEATURE] E#9-S#4, E#10-S#1 오늘의 리뷰 API 연결
  mock-api.json
  next.config.js
  src/components/common/ReviewCard.tsx
  src/components/review/OtherReviewCard.tsx
  src/features/reviews/reviewApi.ts
  src/pages/index.tsx
  src/pages/review/detail/[reviewId].tsx
  src/pages/shop/detail/[id].tsx
  src/types/review.ts
Labels: :sparkles: feature, :1st_place_medal:, 혁진, ❤️‍🔥 리뷰완료

#79 [#78] [FEATURE] E#9-S#2 지역별 소품샵 API 연결
  src/components/MapSidebar/ShopElement.tsx
  src/components/MapSidebar/index.tsx
  src/features/shops/shopApi.ts
  src/pages/map/[areaId].tsx
  src/types/shop.ts
Labels: :sparkles: feature, :1st_place_medal:, 희선

#69 [FEATURE] E#3-S5, S6 리뷰 텍스트 및 태그 입력 + 리뷰 작성완료
  src/components/review/write/ReviewText.tsx
  src/components/review/write/SubmitButton.tsx
  src/components/review/write/TagList.tsx
  src/pages/review/write.tsx
Labels: :sparkles: feature, :1st_place_medal:, 소희

#86 [#85] [FEATURE] E#9-S#7 카테고리별 소품샵 API 연결
  next.config.js
  src/features/shops/shopApi.ts
  src/pages/index.tsx
Labels: :sparkles: feature, :1st_place_medal:, 희선, 🔫 리뷰중

#89 [#84] [FEATURE] E#10-S#5 내가 스크랩한 리뷰 API 연결
  src/features/reviews/reviewApi.ts
  src/pages/review/my/scrap.tsx
  src/types/review.ts
Labels: :sparkles: feature, :1st_place_medal:, 희선, ❤️‍🔥 리뷰완료

#88 [#82] [FEATURE] E#10-S#4 내가 작성한 리뷰 API 연결
  src/components/common/ReviewCard.tsx
  src/features/reviews/reviewApi.ts
  src/pages/review/my/write.tsx
  src/types/review.ts
  src/utils/parseDate.ts
Labels: :sparkles: feature, :1st_place_medal:, 희선, 🔫 리뷰중

#90 [#87] [FEATURE] E#10-S#6 리뷰작성 mutation API
  next.config.js
  src/features/reviews/reviewApi.ts
  src/types/review.ts
Labels: :sparkles: feature, :1st_place_medal:, 혁진, 🔫 리뷰중

#93 [#92] [FEATURE] E#10-S#2 소품샵 상세의 리뷰 API 연결
  src/components/ShopDetail/DetailImageGrid/index.tsx
  src/components/review/ReviewDetailCard.tsx
  src/features/reviews/reviewApi.ts
  src/pages/review/detail/[reviewId].tsx
  src/pages/shop/detail/[id].tsx
  src/types/review.ts
  src/types/shop.ts
Labels: :sparkles: feature, :1st_place_medal:, 혁진, ❤️‍🔥 리뷰완료

#100 [#99] [FEATURE] E#8-S#2 저장한 소품샵 페이지 필터 구현
  src/features/shops/shopApi.ts
  src/pages/shop/collect.tsx
Labels: :sparkles: feature, :1st_place_medal:, 희선, 🔫 리뷰중

#107 [#94] [FEATURE] E#10-S#7 리뷰 좋아요/스크랩 API 연결
  src/components/review/ReviewDetailCard.tsx
  src/features/reviews/reviewApi.ts
  src/pages/review/detail/[reviewId].tsx
  src/types/review.ts
Labels: :sparkles: feature, :1st_place_medal:, 희선, 혁진, 🔫 리뷰중

#105 [#101] [FEATURE] E#8-S#2 리뷰상세 페이지 필터 구현
  src/constants/dropdownOptionList.ts
  src/pages/review/detail/[reviewId].tsx
Labels: :sparkles: feature, :1st_place_medal:, 희선, 🔫 리뷰중

#97 [#96] [BUG] 지도 좌표 검색 실패하는 이슈
  src/hooks/useMap.tsx
  src/map/utils/display.ts
  src/map/utils/search.ts
Labels: :bug: bug, :1st_place_medal:, 혁진, 🔫 리뷰중

#98 [FEATURE] E#7-S#4 리뷰 작성 페이지 조립 + API 연결
  src/components/review/ShopSearch.tsx
  src/components/review/WriteItems/BuyList.tsx
  src/components/review/WriteItems/DropdownItem.tsx
  src/components/review/WriteItems/DropdownPrice.tsx
  src/components/review/WriteItems/ItemsListDiv.tsx
  src/components/review/WriteItems/PriceList.tsx
  src/components/review/WriteItems/index.tsx
  src/components/review/write/PreviewImageList.tsx
  src/components/review/write/ReviewText.tsx
  src/components/review/write/SubmitButton.tsx
  src/components/review/write/TagList.tsx
  src/components/review/write/Title.tsx
  src/constants/dropdownOptionList.ts
  src/pages/review/detail/[reviewId].tsx
  src/pages/review/write.tsx
  src/pages/shop/detail/[id].tsx
  src/types/review.ts
  src/types/shop.ts
Labels: :sparkles: feature, :1st_place_medal:, 소희, 🔫 리뷰중

#103 [#102] [FEATURE] E#8-S#2 메인페이지 카테고리 더보기 필터
  src/components/common/MoreFilter.tsx
  src/features/shops/shopApi.ts
  src/pages/index.tsx
Labels: :sparkles: feature, :1st_place_medal:, 혁진, 🔫 리뷰중

#106 [#104] [FEATURE] E#8-S#2 테마별소품샵 페이지 필터
  src/features/shops/shopApi.ts
  src/pages/shop/theme/[type].tsx
Labels: :sparkles: feature, :1st_place_medal:, 혁진, 🔫 리뷰중

#108 [#000] [FEATURE] E#10-S#3 리뷰 상세페이지 이미지 API 연결
  src/components/review/ReviewDetailCard.tsx
Labels: :sparkles: feature, :1st_place_medal:, 주희, 🔫 리뷰중

#110 [#109] [FEATURE] E#9-S#9 소품샵 상세페이지 리뷰 필터링 API 연결
  src/constants/dropdownOptionList.ts
  src/pages/shop/detail/[id].tsx
Labels: :sparkles: feature, :1st_place_medal:, 주희

#111 [#000] [EDIT] E#7-S-7 소품샵 상세 더미데이터 이미지 제거
  src/components/ShopDetail/DetailImageGrid/index.tsx
Labels: :bug: bug, :3rd_place_medal:, 희선
