Repository TeamSodam/sodam-client, pull requests merged in 2022-06, with the labels that each got.

#161 [#144, #146] 닉네임 중복확인, 이메일 인증 api 연결 리뷰 반영
  src/components/Auth/AcceptTerms.tsx
  src/components/Auth/SignupForm.tsx
  src/components/Auth/SignupOption.tsx
  src/components/common/PersonalInfoInput.tsx
  src/components/review/ReviewDetailCard.tsx
  src/constants/joinInfoList.ts
  src/features/auth/authApi.ts
  src/hooks/useInput.ts
  src/pages/auth/join.tsx
  src/types/auth.ts
Labels: :construction: refactor, :3rd_place_medal:, 희선, 🔫 리뷰중

#160 [#158] [FEATURE] E#11-S#11 로그인 여부에 따른 뷰 분기처리
  .eslintrc.json
  public/assets/ic_search_mobile.svg
  src/components/LocalShopInfo/ShopElement.tsx
  src/components/LocalShopInfo/ShopList.tsx
  src/components/common/EmptyContent.tsx
  src/components/common/Navbar/GlobalNav/Desktop.tsx
  src/components/common/Navbar/GlobalNav/Mobile.tsx
  src/components/common/Navbar/GlobalNav/index.tsx
  src/components/common/Navbar/LocalNav.tsx
  src/components/common/Navbar/NavSearch/index.tsx
  src/features/reviews/reviewApi.ts
  src/features/shops/shopApi.ts
  src/features/users/userApi.ts
  src/features/users/userSlice.ts
  src/libs/.keep
  src/libs/api.ts
  src/pages/auth/login.tsx
  src/pages/map/[areaId].tsx
  src/pages/mypage.tsx
  src/pages/review/my/emptyScrap.tsx
  src/pages/review/my/emptyWrite.tsx
  src/pages/review/my/scrap.tsx
  src/pages/review/my/write.tsx
  src/pages/shop/collect.tsx
  src/pages/shop/collectEmpty.tsx
Labels: :sparkles: feature, :2nd_place_medal:, 혁진, 🔫 리뷰중

#157 [#155, #156] [FEATURE] E#A-S#1,2 배너/이용약관 수정
  public/assets/banner/banner1.png
  public/assets/banner/banner2.png
  public/assets/banner/banner3.png
  public/assets/banner/banner_01_background.svg
  public/assets/banner/banner_01_btn.svg
  public/assets/banner/banner_01_desktop_background.svg
  public/assets/banner/banner_01_desktop_text.svg
  public/assets/banner/banner_01_text.svg
  public/assets/banner/banner_02_background.svg
  public/assets/banner/banner_02_desktop_background.svg
  public/assets/banner/banner_03_background.png
  public/assets/banner/banner_03_btn.svg
  public/assets/banner/banner_03_desktop_background.png
  src/components/BannerList/bannerElements.tsx
  src/components/BannerList/bannerSrcList.tsx
  src/components/BannerList/index.tsx
  src/components/common/Banner.tsx
  src/components/common/Footer.tsx
  src/components/common/MainSlider.tsx
  src/constants/sodamContactList.ts
  src/constants/sodamDocList.ts
Labels: :sparkles: feature, :3rd_place_medal:, 혁진, 🔫 리뷰중

#153 [#142] [FEATURE] E#13-S#4 소품샵 상세페이지 반응형
  public/assets/ic_address_toggle.svg
  public/assets/ic_copy.svg
  public/assets/ic_pin_star.svg
  src/components/ShopDetail/DetailImageGrid/index.tsx
  src/components/ShopDetail/DetailInfo/DesktopLayout.tsx
  src/components/ShopDetail/DetailInfo/IconContent.tsx
  src/components/ShopDetail/DetailInfo/MobileLayout.tsx
  src/components/ShopDetail/DetailInfo/index.tsx
  src/components/ShopDetail/DetailShopAddress/index.tsx
  src/components/common/DropDownFilter.tsx
  src/components/common/PageNaviagator.tsx
  src/components/common/WriteReviewLink.tsx
  src/constants/availableWidths.ts
  src/hooks/useWindowSize.ts
  src/map/overlays/miniTooltip.tsx
  src/pages/_app.tsx
  src/pages/review/my/write.tsx
  src/pages/shop/detail/[id].tsx
  src/styles/mixin.ts
  src/types/styled.d.ts
Labels: :sparkles: feature, :2nd_place_medal:, 혁진, 🔫 리뷰중

#166 [#154] E#13-S#5 모바일 카드 반응형 구현
  src/components/BannerList/index.tsx
  src/components/common/MainSlider.tsx
  src/components/common/ReviewCard.tsx
  src/components/common/ShopCard.tsx
  src/components/common/ShopCardRank.tsx
  src/pages/index.tsx
  src/pages/review/my/scrap.tsx
  src/pages/review/my/write.tsx
  src/pages/shop/collect.tsx
  src/pages/shop/theme/[type].tsx
Labels: :sparkles: feature, :3rd_place_medal:, 소희

#169 [#167][FEATURE] E#12-S#5~7 데스크탑 나머지 페이지 반응형
  src/components/Icons/IcDeleteRound.tsx
  src/components/Icons/IcLikeReview.tsx
  src/components/Icons/IcScrapReview.tsx
  src/components/ThemeSelector/ThemeElement.tsx
  src/components/ThemeSelector/index.tsx
  src/components/common/DropDownFilter.tsx
  src/components/common/EmptyContent.tsx
  src/components/common/FilterDiv.tsx
  src/components/common/Layout.tsx
  src/components/common/MainSlider.tsx
  src/components/common/MoreFilter.tsx
  src/components/common/Navbar/LocalNav.tsx
  src/components/common/WriteReviewLink.tsx
  src/components/review/ImageCard.tsx
  src/components/review/ImageSlider.tsx
  src/components/review/OtherReview/Container/index.tsx
  src/components/review/ReviewDetailCard.tsx
  src/components/review/ShopSearch.tsx
  src/components/review/ShopSearchList.tsx
  src/components/review/WriteItems/BuyList.tsx
  src/components/review/WriteItems/DropdownItem.tsx
  src/components/review/WriteItems/DropdownPrice.tsx
  src/components/review/WriteItems/ItemsListDiv.tsx
  src/components/review/WriteItems/PriceList.tsx
  src/components/review/WriteItems/index.tsx
  src/components/review/write/PreviewImageList.tsx
  src/components/review/write/PreviewImageMain.tsx
  src/components/review/write/ReviewText.tsx
  src/components/review/write/SubmitButton.tsx
  src/components/review/write/TagList.tsx
  src/components/review/write/Title.tsx
  src/features/reviews/reviewApi.ts
  src/pages/index.tsx
  src/pages/mypage.tsx
  src/pages/review/detail/[reviewId].tsx
  src/pages/review/my/scrap.tsx
  src/pages/review/my/write.tsx
  src/pages/review/write.tsx
  src/pages/shop/collect.tsx
  src/pages/shop/theme/[type].tsx
Labels: :sparkles: feature, :3rd_place_medal:, 소희

#173 [#170][FEATURE] E#13-S#6~9 나머지 페이지 모바일 반응형
  next.config.js
  src/components/ShopDetail/DetailShopAddress/index.tsx
  src/components/ThemeSelector/ThemeElement.tsx
  src/components/ThemeSelector/index.tsx
  src/components/common/DropDownFilter.tsx
  src/components/common/EmptyContent.tsx
  src/components/common/FilterDiv.tsx
  src/components/common/Footer.tsx
  src/components/common/MoreFilter.tsx
  src/components/common/Navbar/GlobalNav/Mobile.tsx
  src/components/common/Navbar/LocalNav.tsx
  src/components/common/PageNaviagator.tsx
  src/components/common/WriteReviewLink.tsx
  src/components/review/ImageCard.tsx
  src/components/review/ImageSlider.tsx
  src/components/review/OtherReview/Container/index.tsx
  src/components/review/ReviewDetailCard.tsx
  src/components/review/ShopSearch.tsx
  src/components/review/ShopSearchList.tsx
  src/components/review/WriteItems/BuyList.tsx
  src/components/review/WriteItems/DropdownItem.tsx
  src/components/review/WriteItems/DropdownPrice.tsx
  src/components/review/WriteItems/ItemsListDiv.tsx
  src/components/review/WriteItems/PriceList.tsx
  src/components/review/WriteItems/index.tsx
  src/components/review/write/PreviewImageList.tsx
  src/components/review/write/PreviewImageMain.tsx
  src/components/review/write/ReviewText.tsx
  src/components/review/write/SubmitButton.tsx
  src/components/review/write/TagList.tsx
  src/components/review/write/Title.tsx
  src/pages/index.tsx
  src/pages/map/index.tsx
  src/pages/review/detail/[reviewId].tsx
  src/pages/review/my/scrap.tsx
  src/pages/review/my/write.tsx
  src/pages/review/write.tsx
  src/pages/shop/collect.tsx
  src/pages/shop/detail/[id].tsx
  src/pages/shop/theme/[type].tsx
Labels: :sparkles: feature, :3rd_place_medal:, 소희, 🔫 리뷰중

#179 [#177] [FEATURE] E#X-S#9 중복위치마커 처리
  public/assets/logo.svg
  src/components/LocalShopInfo/ShopList.tsx
  src/components/LocalShopInfo/index.tsx
  src/components/common/Loader.tsx
  src/features/map/mapSlice.ts
  src/hooks/useMap.tsx
  src/map/data/latlng.ts
  src/map/overlays/tooltip.tsx
  src/map/utils/display.ts
  src/pages/map/[areaId].tsx
  src/types/map.ts
Labels: :sparkles: feature, 혁진, 🔫 리뷰중

#178 [#165] [FEATURE] E#11-S#6 회원가입 약관 뷰 제작
  public/assets/ic_termsClose.svg
  src/components/Auth/AcceptTerms.tsx
  src/components/Auth/DetailTerms.tsx
  src/components/Auth/TermsContents.ts
  src/constants/TermsContents.ts
Labels: :sparkles: feature, :3rd_place_medal:, 희선, 🔫 리뷰중

#176 [#174] [FEATURE] E#11-S#11 미인증유저 필터링
  src/components/LocalShopInfo/ShopList.tsx
  src/components/ShopDetail/DetailInfo/index.tsx
  src/components/common/Navbar/GlobalNav/index.tsx
  src/components/common/WriteReviewLink.tsx
  src/components/review/ReviewDetailCard.tsx
  src/pages/auth/login.tsx
  src/pages/review/my/write.tsx
  src/pages/shop/detail/[id].tsx
Labels: :sparkles: feature, :2nd_place_medal:, 혁진, 🔫 리뷰중

#171 [#168] [FEATURE] E#11-S#12 로그인 유지
  mock-api.json
  next.config.js
  package.json
  routes.json
  src/app/persistToken.ts
  src/app/store.ts
  src/components/common/MoreFilter.tsx
  src/components/common/Navbar/GlobalNav/index.tsx
  src/components/common/Navbar/NavSearch/index.tsx
  src/components/review/ShopSearch.tsx
  src/features/auth/authApi.ts
  src/features/reviews/reviewApi.ts
  src/features/shops/shopApi.ts
  src/features/users/userApi.ts
  src/libs/api.ts
  src/pages/auth/login.tsx
  src/pages/index.tsx
  src/pages/review/my/scrap.tsx
  src/pages/review/my/write.tsx
  src/pages/shop/collect.tsx
  src/utils/decode-jwt.ts
  yarn.lock
Labels: :sparkles: feature, :2nd_place_medal:, 혁진, 🔫 리뷰중
